stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Build your project here"

deploy:
  stage: deploy
  script:
    - echo "Deploy your project here"
webhook:
  stage: deploy
  script:
    - curl -X POST https://webhooks.hostinger.com/deploy/50f1f20eeecf706ecafe2b288431c758
  only:
    - test
