name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Выберите нужную ОС, например, ubuntu-20.04
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.key }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: SSH to VPS and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.key }} root@154.56.51.204 "cd /party-wave && npm install && npm run start:prod"

